### PR TITLE
Added journal week 2 and cascading style sheet

### PR DESCRIPTION
**Pull request by kmattiko**

### CODE REVIEW

**Comment by melrodbos** [comment]
Great Job Kim! :+1: I agree with you on how challenging JavaScript is to learn and apply.

**Comment by melrodbos** [comment]
Great journal entry Kim! Right on point with how I feel:+1:

**Comment by gatorpazz** [comment]
gr8 journal entry m8, I r8, 8/8 :+1:

**Comment by kmattiko** [comment]
Thanks all, I'll make that change Phil, good catch :)

**Pull request merged**
